# Generated by Django 2.2.10 on 2020-11-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifty', '0002_auto_20201126_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='ong',
            name='donation_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ong',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
