# Generated by Django 2.2.10 on 2020-12-01 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifty', '0004_remove_ong_cnas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ong',
            name='short_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
